### ISSUE TITLE
unsupported RF power for TX

### ISSUE THREAD

**Issue by mazareth** [Lora-net/picoGW_packet_forwarder#3]
Hello,
This morning everything work fine. But now i have a problem. according to me, nothing really change.
When my device try to join the ack message is not sent due to unsupported RF power.

Error message
```
JSON up: {"stat":{"time":"2017-11-20 11:10:45 GMT","rxnb":3,"rxok":2,"rxfw":2,"ackr":66.7,"dwnb":0,"txnb":0}}
INFO: [up] PUSH_ACK received in 40 ms
INFO: [down] PULL_ACK received in 37 ms
INFO: [down] PULL_RESP received  - token[45:133] :)

JSON down: {"txpk":{"imme":false,"tmst":308984636,"freq":869.525,"rfch":0,"powe":27,"modu":"LORA","datr":"SF12BW125","codr":"4/5","ipol":true,"size":33,"data":"IKQ2bcZ55m5IAetqRuLqrdgeL8D3bu/4MXEzWkrahGlp"}}
ERROR: Packet REJECTED, unsupported RF power for TX - 27
INFO: [down] PULL_ACK received in 38 ms
```

I found a similar issue, but my antenna gain doesn't change. It's 0dbi.
https://github.com/brocaar/loraserver/issues/121

Have you an idea? Where is the problem? How can i solve it properly?

**Comment by mcoracin** [comment]
The server request a 27dBm downlink, but the picoGW does not support it.
You can workaround this issue by faking a 27dBm entry in the global_conf.json file. To do this replace:
```
		"tx_lut_15": {
			/* TX gain table, index 15 */
			"pa_gain": 0,
			"mix_gain": 12,
			"rf_power": 20,
			"dig_gain": 3
```
with
```
		"tx_lut_15": {
			/* TX gain table, index 15 */
			"pa_gain": 0,
			"mix_gain": 12,
			"rf_power": 27,
			"dig_gain": 3
```

This should work then.

**Comment by mazareth** [comment]
Thanks that working. 
The problem come from my server request if i understand well. I will try to solve that later...
